kind = "mobile"
previewPath = "/"
title = "Quran Listener"
version = "1.0.0"
id = "artifacts/quran-listener"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 22069

[services.development]
run = "pnpm --filter @workspace/quran-listener run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/quran-listener", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/quran-listener", "run", "serve" ]

[services.env]
PORT = "22069"
BASE_PATH = "/"
