// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/repeat-ideas/ActionStrip.tsx": () => import("../components/mockups/repeat-ideas/ActionStrip.tsx"),
  "./components/mockups/repeat-ideas/LongpressMenu.tsx": () => import("../components/mockups/repeat-ideas/LongpressMenu.tsx"),
  "./components/mockups/repeat-ideas/ReciterSheet.tsx": () => import("../components/mockups/repeat-ideas/ReciterSheet.tsx")
};
